server:
  port: 9527
spring:
  application:
    name: microservicecloud-zuul-gateway


eureka:
  client:     #客户端注册进eureka服务列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
# 单机模式    defaultZone: http://localhost:7001/eureka              #服务注册地址
  instance:
    instance-id: gateway-9627.com                #修改host文件主机名称：服务名称的修改 -自定义服务名称信息
    prefer-ip-address: true                                 # 访问路径可以显示ip地址
